import { createConstants } from 'utils';

export default createConstants(
  'EMAIL_ARRAY_FETCH',
  'EMAIL_ARRAY_REQUEST',
  'EMAIL_ARRAY_FETCH_SUCCESS',
  'EMAIL_ARRAY_FETCH_ERROR',
  'EMAIL_SHOW_ONE_FLAG',
  'EMAIL_SHOW_ALL_FLAGS',
  'EMAIL_SHOW_COMPLETE',
  'REQUESTING_EMAIL_UNFLAG',
  'EMAIL_UNFLAG_ERROR',
  'EMAIL_UNFLAG_SUCCESS',
  'EMAIL_MARK_READ_SUCCESS',
  'EMAIL_MARK_READ_ERROR',
);
