import { createConstants } from 'utils';

export default createConstants(
  'FILTER_ARRAY_FETCH',
  'FILTER_ARRAY_REQUEST',
  'FILTER_ARRAY_FETCH_SUCCESS',
  'FILTER_ARRAY_FETCH_ERROR',

  'FILTER_TYPE_SELECT',

  'FILTER_TYPE_ADD',
  'FILTER_TYPE_POST_SUCCESS',
  'FILTER_TYPE_POST_REQUEST',
  'FILTER_TYPE_POST_ERROR',

  'FILTER_ADD_FLAG_KEYWORD',
  'FILTER_FLAG_POST_SUCCESS',
  'FILTER_FLAG_POST_REQUEST',
  'FILTER_FLAG_POST_ERROR',

  'FILTER_REMOVE_FLAG_KEYWORD',
  'FILTER_FLAG_REMOVE_SUCCESS',
  'FILTER_FLAG_REMOVE_REQUEST',
  'FILTER_FLAG_REMOVE_ERROR',
);
