import { createConstants } from 'utils';

export default createConstants(
  'APPLICATION_LOADED',
  'LOGIN_SUBMITTED',
  'LOGIN_SUCCEEDED',
  'LOGIN_FAILED',
  'USER_FETCHED',
  'USER_FETCH_SUCCEEDED',
  'USER_FETCH_FAILED',
  'TOKEN_DELETED',
  'TOKEN_DELETE_SUCCEEDED',
  'TOKEN_DELETE_FAILED',
);
